name: deploy to lambda
on:
  # Trigger the workflow on push or pull request,
  # but only for the main branch
  commit:
    branches:
      - main
jobs:

  deploy_source:
    name: deploy lambda from source
    runs-on: windows
    steps:
      - name: checkout source code
        uses: actions/checkout@v1
      - name: default deploy
        uses: appleboy/lambda-action@master
        with:
          aws_access_key_id: AKIAUOFRSJPQHTXHKDNO
          aws_secret_access_key: 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
          aws_region: ap-south-1
          function_name: remove-duplicate-values
          source: remove-duplicate-values/removeduplicate.py
